# Generated by Django 3.1 on 2020-08-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='date_posted',
        ),
    ]
